spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # the address of the kafka server to connect to
      bindings:
        messages-in:
          destination: messages # kafka topic used both for the inbound and outbound streams
          contentType: application/json
        messages-out:
          destination: messages
          contentType: application/json